CREATE TABLE IF NOT EXISTS coffees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    roast_level VARCHAR(50),
    origin VARCHAR(100),
    price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);